package lb.com.db.bo;

import java.math.BigDecimal;
import java.util.Date;

public class OrdOrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    private Long orderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.ORDER_ID
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.CATEGORY_ID
     *
     * @mbggenerated
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.BRANCH_ID
     *
     * @mbggenerated
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.CONTRACT_ID
     *
     * @mbggenerated
     */
    private Long contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.ORDER_PACK_ID
     *
     * @mbggenerated
     */
    private Long orderPackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.SUPP_GOODS_ID
     *
     * @mbggenerated
     */
    private Long suppGoodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.PRICE
     *
     * @mbggenerated
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.ACTUAL_SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    private Long actualSettlementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    private Long settlementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.QUANTITY
     *
     * @mbggenerated
     */
    private Long quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.TOTAL_SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    private Long totalSettlementPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.VISIT_TIME
     *
     * @mbggenerated
     */
    private Date visitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.NEED_RESOURCE_CONFIRM
     *
     * @mbggenerated
     */
    private String needResourceConfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.RESOURCE_STATUS
     *
     * @mbggenerated
     */
    private String resourceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.INFO_STATUS
     *
     * @mbggenerated
     */
    private String infoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.MARKET_PRICE
     *
     * @mbggenerated
     */
    private Long marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.PERFORM_STATUS
     *
     * @mbggenerated
     */
    private String performStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.PERFORM_STATUS_CODE
     *
     * @mbggenerated
     */
    private String performStatusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.CANCEL_STRATEGY
     *
     * @mbggenerated
     */
    private String cancelStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.SETTLEMENT_STATUS
     *
     * @mbggenerated
     */
    private String settlementStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.MAIN_ITEM
     *
     * @mbggenerated
     */
    private String mainItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.SUPP_GOODS_NAME
     *
     * @mbggenerated
     */
    private String suppGoodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.SUPPLIER_ID
     *
     * @mbggenerated
     */
    private Long supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.DEDUCT_TYPE
     *
     * @mbggenerated
     */
    private String deductType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.CERT_CONFIRM_STATUS
     *
     * @mbggenerated
     */
    private String certConfirmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.CANCEL_CERT_CONFIRM_STATUS
     *
     * @mbggenerated
     */
    private String cancelCertConfirmStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.DEDUCT_AMOUNT
     *
     * @mbggenerated
     */
    private Long deductAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.BOOK_LIMIT_TYPE
     *
     * @mbggenerated
     */
    private String bookLimitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.LAST_CANCEL_TIME
     *
     * @mbggenerated
     */
    private Date lastCancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.ORDER_MEMO
     *
     * @mbggenerated
     */
    private String orderMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.TICKET_TYPE
     *
     * @mbggenerated
     */
    private String ticketType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.PAYMENT_STATUS
     *
     * @mbggenerated
     */
    private String paymentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.SUPP_PRODUCT_NAME
     *
     * @mbggenerated
     */
    private String suppProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.TOTAL_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.MANAGER_ID
     *
     * @mbggenerated
     */
    private Long managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.BU_CODE
     *
     * @mbggenerated
     */
    private String buCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.ATTRIBUTION_ID
     *
     * @mbggenerated
     */
    private BigDecimal attributionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.REAL_BU_TYPE
     *
     * @mbggenerated
     */
    private String realBuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_ORDER_ITEM.REFUND_RULES
     *
     * @mbggenerated
     */
    private String refundRules;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.ORDER_ITEM_ID
     *
     * @return the value of ORD_ORDER_ITEM.ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    public Long getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.ORDER_ITEM_ID
     *
     * @param orderItemId the value for ORD_ORDER_ITEM.ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.ORDER_ID
     *
     * @return the value of ORD_ORDER_ITEM.ORDER_ID
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.ORDER_ID
     *
     * @param orderId the value for ORD_ORDER_ITEM.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.CATEGORY_ID
     *
     * @return the value of ORD_ORDER_ITEM.CATEGORY_ID
     *
     * @mbggenerated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.CATEGORY_ID
     *
     * @param categoryId the value for ORD_ORDER_ITEM.CATEGORY_ID
     *
     * @mbggenerated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.BRANCH_ID
     *
     * @return the value of ORD_ORDER_ITEM.BRANCH_ID
     *
     * @mbggenerated
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.BRANCH_ID
     *
     * @param branchId the value for ORD_ORDER_ITEM.BRANCH_ID
     *
     * @mbggenerated
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.CONTRACT_ID
     *
     * @return the value of ORD_ORDER_ITEM.CONTRACT_ID
     *
     * @mbggenerated
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.CONTRACT_ID
     *
     * @param contractId the value for ORD_ORDER_ITEM.CONTRACT_ID
     *
     * @mbggenerated
     */
    public void setContractId(Long contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.ORDER_PACK_ID
     *
     * @return the value of ORD_ORDER_ITEM.ORDER_PACK_ID
     *
     * @mbggenerated
     */
    public Long getOrderPackId() {
        return orderPackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.ORDER_PACK_ID
     *
     * @param orderPackId the value for ORD_ORDER_ITEM.ORDER_PACK_ID
     *
     * @mbggenerated
     */
    public void setOrderPackId(Long orderPackId) {
        this.orderPackId = orderPackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.SUPP_GOODS_ID
     *
     * @return the value of ORD_ORDER_ITEM.SUPP_GOODS_ID
     *
     * @mbggenerated
     */
    public Long getSuppGoodsId() {
        return suppGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.SUPP_GOODS_ID
     *
     * @param suppGoodsId the value for ORD_ORDER_ITEM.SUPP_GOODS_ID
     *
     * @mbggenerated
     */
    public void setSuppGoodsId(Long suppGoodsId) {
        this.suppGoodsId = suppGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.PRODUCT_NAME
     *
     * @return the value of ORD_ORDER_ITEM.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.PRODUCT_NAME
     *
     * @param productName the value for ORD_ORDER_ITEM.PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.PRICE
     *
     * @return the value of ORD_ORDER_ITEM.PRICE
     *
     * @mbggenerated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.PRICE
     *
     * @param price the value for ORD_ORDER_ITEM.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.ACTUAL_SETTLEMENT_PRICE
     *
     * @return the value of ORD_ORDER_ITEM.ACTUAL_SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    public Long getActualSettlementPrice() {
        return actualSettlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.ACTUAL_SETTLEMENT_PRICE
     *
     * @param actualSettlementPrice the value for ORD_ORDER_ITEM.ACTUAL_SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    public void setActualSettlementPrice(Long actualSettlementPrice) {
        this.actualSettlementPrice = actualSettlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.SETTLEMENT_PRICE
     *
     * @return the value of ORD_ORDER_ITEM.SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    public Long getSettlementPrice() {
        return settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.SETTLEMENT_PRICE
     *
     * @param settlementPrice the value for ORD_ORDER_ITEM.SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    public void setSettlementPrice(Long settlementPrice) {
        this.settlementPrice = settlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.QUANTITY
     *
     * @return the value of ORD_ORDER_ITEM.QUANTITY
     *
     * @mbggenerated
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.QUANTITY
     *
     * @param quantity the value for ORD_ORDER_ITEM.QUANTITY
     *
     * @mbggenerated
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.TOTAL_SETTLEMENT_PRICE
     *
     * @return the value of ORD_ORDER_ITEM.TOTAL_SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    public Long getTotalSettlementPrice() {
        return totalSettlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.TOTAL_SETTLEMENT_PRICE
     *
     * @param totalSettlementPrice the value for ORD_ORDER_ITEM.TOTAL_SETTLEMENT_PRICE
     *
     * @mbggenerated
     */
    public void setTotalSettlementPrice(Long totalSettlementPrice) {
        this.totalSettlementPrice = totalSettlementPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.VISIT_TIME
     *
     * @return the value of ORD_ORDER_ITEM.VISIT_TIME
     *
     * @mbggenerated
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.VISIT_TIME
     *
     * @param visitTime the value for ORD_ORDER_ITEM.VISIT_TIME
     *
     * @mbggenerated
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.NEED_RESOURCE_CONFIRM
     *
     * @return the value of ORD_ORDER_ITEM.NEED_RESOURCE_CONFIRM
     *
     * @mbggenerated
     */
    public String getNeedResourceConfirm() {
        return needResourceConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.NEED_RESOURCE_CONFIRM
     *
     * @param needResourceConfirm the value for ORD_ORDER_ITEM.NEED_RESOURCE_CONFIRM
     *
     * @mbggenerated
     */
    public void setNeedResourceConfirm(String needResourceConfirm) {
        this.needResourceConfirm = needResourceConfirm == null ? null : needResourceConfirm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.RESOURCE_STATUS
     *
     * @return the value of ORD_ORDER_ITEM.RESOURCE_STATUS
     *
     * @mbggenerated
     */
    public String getResourceStatus() {
        return resourceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.RESOURCE_STATUS
     *
     * @param resourceStatus the value for ORD_ORDER_ITEM.RESOURCE_STATUS
     *
     * @mbggenerated
     */
    public void setResourceStatus(String resourceStatus) {
        this.resourceStatus = resourceStatus == null ? null : resourceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.INFO_STATUS
     *
     * @return the value of ORD_ORDER_ITEM.INFO_STATUS
     *
     * @mbggenerated
     */
    public String getInfoStatus() {
        return infoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.INFO_STATUS
     *
     * @param infoStatus the value for ORD_ORDER_ITEM.INFO_STATUS
     *
     * @mbggenerated
     */
    public void setInfoStatus(String infoStatus) {
        this.infoStatus = infoStatus == null ? null : infoStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.MARKET_PRICE
     *
     * @return the value of ORD_ORDER_ITEM.MARKET_PRICE
     *
     * @mbggenerated
     */
    public Long getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.MARKET_PRICE
     *
     * @param marketPrice the value for ORD_ORDER_ITEM.MARKET_PRICE
     *
     * @mbggenerated
     */
    public void setMarketPrice(Long marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.PERFORM_STATUS
     *
     * @return the value of ORD_ORDER_ITEM.PERFORM_STATUS
     *
     * @mbggenerated
     */
    public String getPerformStatus() {
        return performStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.PERFORM_STATUS
     *
     * @param performStatus the value for ORD_ORDER_ITEM.PERFORM_STATUS
     *
     * @mbggenerated
     */
    public void setPerformStatus(String performStatus) {
        this.performStatus = performStatus == null ? null : performStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.PERFORM_STATUS_CODE
     *
     * @return the value of ORD_ORDER_ITEM.PERFORM_STATUS_CODE
     *
     * @mbggenerated
     */
    public String getPerformStatusCode() {
        return performStatusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.PERFORM_STATUS_CODE
     *
     * @param performStatusCode the value for ORD_ORDER_ITEM.PERFORM_STATUS_CODE
     *
     * @mbggenerated
     */
    public void setPerformStatusCode(String performStatusCode) {
        this.performStatusCode = performStatusCode == null ? null : performStatusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.CANCEL_STRATEGY
     *
     * @return the value of ORD_ORDER_ITEM.CANCEL_STRATEGY
     *
     * @mbggenerated
     */
    public String getCancelStrategy() {
        return cancelStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.CANCEL_STRATEGY
     *
     * @param cancelStrategy the value for ORD_ORDER_ITEM.CANCEL_STRATEGY
     *
     * @mbggenerated
     */
    public void setCancelStrategy(String cancelStrategy) {
        this.cancelStrategy = cancelStrategy == null ? null : cancelStrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.CONTENT
     *
     * @return the value of ORD_ORDER_ITEM.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.CONTENT
     *
     * @param content the value for ORD_ORDER_ITEM.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.SETTLEMENT_STATUS
     *
     * @return the value of ORD_ORDER_ITEM.SETTLEMENT_STATUS
     *
     * @mbggenerated
     */
    public String getSettlementStatus() {
        return settlementStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.SETTLEMENT_STATUS
     *
     * @param settlementStatus the value for ORD_ORDER_ITEM.SETTLEMENT_STATUS
     *
     * @mbggenerated
     */
    public void setSettlementStatus(String settlementStatus) {
        this.settlementStatus = settlementStatus == null ? null : settlementStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.MAIN_ITEM
     *
     * @return the value of ORD_ORDER_ITEM.MAIN_ITEM
     *
     * @mbggenerated
     */
    public String getMainItem() {
        return mainItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.MAIN_ITEM
     *
     * @param mainItem the value for ORD_ORDER_ITEM.MAIN_ITEM
     *
     * @mbggenerated
     */
    public void setMainItem(String mainItem) {
        this.mainItem = mainItem == null ? null : mainItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.PRODUCT_ID
     *
     * @return the value of ORD_ORDER_ITEM.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.PRODUCT_ID
     *
     * @param productId the value for ORD_ORDER_ITEM.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.SUPP_GOODS_NAME
     *
     * @return the value of ORD_ORDER_ITEM.SUPP_GOODS_NAME
     *
     * @mbggenerated
     */
    public String getSuppGoodsName() {
        return suppGoodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.SUPP_GOODS_NAME
     *
     * @param suppGoodsName the value for ORD_ORDER_ITEM.SUPP_GOODS_NAME
     *
     * @mbggenerated
     */
    public void setSuppGoodsName(String suppGoodsName) {
        this.suppGoodsName = suppGoodsName == null ? null : suppGoodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.SUPPLIER_ID
     *
     * @return the value of ORD_ORDER_ITEM.SUPPLIER_ID
     *
     * @mbggenerated
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.SUPPLIER_ID
     *
     * @param supplierId the value for ORD_ORDER_ITEM.SUPPLIER_ID
     *
     * @mbggenerated
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.DEDUCT_TYPE
     *
     * @return the value of ORD_ORDER_ITEM.DEDUCT_TYPE
     *
     * @mbggenerated
     */
    public String getDeductType() {
        return deductType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.DEDUCT_TYPE
     *
     * @param deductType the value for ORD_ORDER_ITEM.DEDUCT_TYPE
     *
     * @mbggenerated
     */
    public void setDeductType(String deductType) {
        this.deductType = deductType == null ? null : deductType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.CERT_CONFIRM_STATUS
     *
     * @return the value of ORD_ORDER_ITEM.CERT_CONFIRM_STATUS
     *
     * @mbggenerated
     */
    public String getCertConfirmStatus() {
        return certConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.CERT_CONFIRM_STATUS
     *
     * @param certConfirmStatus the value for ORD_ORDER_ITEM.CERT_CONFIRM_STATUS
     *
     * @mbggenerated
     */
    public void setCertConfirmStatus(String certConfirmStatus) {
        this.certConfirmStatus = certConfirmStatus == null ? null : certConfirmStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.CANCEL_CERT_CONFIRM_STATUS
     *
     * @return the value of ORD_ORDER_ITEM.CANCEL_CERT_CONFIRM_STATUS
     *
     * @mbggenerated
     */
    public String getCancelCertConfirmStatus() {
        return cancelCertConfirmStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.CANCEL_CERT_CONFIRM_STATUS
     *
     * @param cancelCertConfirmStatus the value for ORD_ORDER_ITEM.CANCEL_CERT_CONFIRM_STATUS
     *
     * @mbggenerated
     */
    public void setCancelCertConfirmStatus(String cancelCertConfirmStatus) {
        this.cancelCertConfirmStatus = cancelCertConfirmStatus == null ? null : cancelCertConfirmStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.DEDUCT_AMOUNT
     *
     * @return the value of ORD_ORDER_ITEM.DEDUCT_AMOUNT
     *
     * @mbggenerated
     */
    public Long getDeductAmount() {
        return deductAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.DEDUCT_AMOUNT
     *
     * @param deductAmount the value for ORD_ORDER_ITEM.DEDUCT_AMOUNT
     *
     * @mbggenerated
     */
    public void setDeductAmount(Long deductAmount) {
        this.deductAmount = deductAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.BOOK_LIMIT_TYPE
     *
     * @return the value of ORD_ORDER_ITEM.BOOK_LIMIT_TYPE
     *
     * @mbggenerated
     */
    public String getBookLimitType() {
        return bookLimitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.BOOK_LIMIT_TYPE
     *
     * @param bookLimitType the value for ORD_ORDER_ITEM.BOOK_LIMIT_TYPE
     *
     * @mbggenerated
     */
    public void setBookLimitType(String bookLimitType) {
        this.bookLimitType = bookLimitType == null ? null : bookLimitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.LAST_CANCEL_TIME
     *
     * @return the value of ORD_ORDER_ITEM.LAST_CANCEL_TIME
     *
     * @mbggenerated
     */
    public Date getLastCancelTime() {
        return lastCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.LAST_CANCEL_TIME
     *
     * @param lastCancelTime the value for ORD_ORDER_ITEM.LAST_CANCEL_TIME
     *
     * @mbggenerated
     */
    public void setLastCancelTime(Date lastCancelTime) {
        this.lastCancelTime = lastCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.ORDER_MEMO
     *
     * @return the value of ORD_ORDER_ITEM.ORDER_MEMO
     *
     * @mbggenerated
     */
    public String getOrderMemo() {
        return orderMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.ORDER_MEMO
     *
     * @param orderMemo the value for ORD_ORDER_ITEM.ORDER_MEMO
     *
     * @mbggenerated
     */
    public void setOrderMemo(String orderMemo) {
        this.orderMemo = orderMemo == null ? null : orderMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.TICKET_TYPE
     *
     * @return the value of ORD_ORDER_ITEM.TICKET_TYPE
     *
     * @mbggenerated
     */
    public String getTicketType() {
        return ticketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.TICKET_TYPE
     *
     * @param ticketType the value for ORD_ORDER_ITEM.TICKET_TYPE
     *
     * @mbggenerated
     */
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType == null ? null : ticketType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.PAYMENT_STATUS
     *
     * @return the value of ORD_ORDER_ITEM.PAYMENT_STATUS
     *
     * @mbggenerated
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.PAYMENT_STATUS
     *
     * @param paymentStatus the value for ORD_ORDER_ITEM.PAYMENT_STATUS
     *
     * @mbggenerated
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus == null ? null : paymentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.ORDER_STATUS
     *
     * @return the value of ORD_ORDER_ITEM.ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.ORDER_STATUS
     *
     * @param orderStatus the value for ORD_ORDER_ITEM.ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.SUPP_PRODUCT_NAME
     *
     * @return the value of ORD_ORDER_ITEM.SUPP_PRODUCT_NAME
     *
     * @mbggenerated
     */
    public String getSuppProductName() {
        return suppProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.SUPP_PRODUCT_NAME
     *
     * @param suppProductName the value for ORD_ORDER_ITEM.SUPP_PRODUCT_NAME
     *
     * @mbggenerated
     */
    public void setSuppProductName(String suppProductName) {
        this.suppProductName = suppProductName == null ? null : suppProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.TOTAL_AMOUNT
     *
     * @return the value of ORD_ORDER_ITEM.TOTAL_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.TOTAL_AMOUNT
     *
     * @param totalAmount the value for ORD_ORDER_ITEM.TOTAL_AMOUNT
     *
     * @mbggenerated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.MANAGER_ID
     *
     * @return the value of ORD_ORDER_ITEM.MANAGER_ID
     *
     * @mbggenerated
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.MANAGER_ID
     *
     * @param managerId the value for ORD_ORDER_ITEM.MANAGER_ID
     *
     * @mbggenerated
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.BU_CODE
     *
     * @return the value of ORD_ORDER_ITEM.BU_CODE
     *
     * @mbggenerated
     */
    public String getBuCode() {
        return buCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.BU_CODE
     *
     * @param buCode the value for ORD_ORDER_ITEM.BU_CODE
     *
     * @mbggenerated
     */
    public void setBuCode(String buCode) {
        this.buCode = buCode == null ? null : buCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.ATTRIBUTION_ID
     *
     * @return the value of ORD_ORDER_ITEM.ATTRIBUTION_ID
     *
     * @mbggenerated
     */
    public BigDecimal getAttributionId() {
        return attributionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.ATTRIBUTION_ID
     *
     * @param attributionId the value for ORD_ORDER_ITEM.ATTRIBUTION_ID
     *
     * @mbggenerated
     */
    public void setAttributionId(BigDecimal attributionId) {
        this.attributionId = attributionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.REAL_BU_TYPE
     *
     * @return the value of ORD_ORDER_ITEM.REAL_BU_TYPE
     *
     * @mbggenerated
     */
    public String getRealBuType() {
        return realBuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.REAL_BU_TYPE
     *
     * @param realBuType the value for ORD_ORDER_ITEM.REAL_BU_TYPE
     *
     * @mbggenerated
     */
    public void setRealBuType(String realBuType) {
        this.realBuType = realBuType == null ? null : realBuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_ORDER_ITEM.REFUND_RULES
     *
     * @return the value of ORD_ORDER_ITEM.REFUND_RULES
     *
     * @mbggenerated
     */
    public String getRefundRules() {
        return refundRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_ORDER_ITEM.REFUND_RULES
     *
     * @param refundRules the value for ORD_ORDER_ITEM.REFUND_RULES
     *
     * @mbggenerated
     */
    public void setRefundRules(String refundRules) {
        this.refundRules = refundRules == null ? null : refundRules.trim();
    }
}