package lb.com.db.dao;

import lb.com.db.bo.OrdOrderItem;

public interface OrdOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_ITEM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_ITEM
     *
     * @mbggenerated
     */
    int insert(OrdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_ITEM
     *
     * @mbggenerated
     */
    int insertSelective(OrdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_ITEM
     *
     * @mbggenerated
     */
    OrdOrderItem selectByPrimaryKey(Long orderItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_ITEM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrdOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_ITEM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrdOrderItem record);
}